# application port
server:
  port: 8888
  error:
    include-stacktrace: always
  servlet:
    context-path: /tbms_service

# spring setting
spring:
  profiles: default
  datasource:
    url: jdbc:postgresql://58.84.1.74:5432/tbms-dev
    username: admin
    password: 123
    sql-script-encoding: UTF-8
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    root: info
    org.spring.framework: info
    com.shop.tbms: debug

# firebase
firebase:
  admin-key: tbms-firebase-firebase-adminsdk-l0zvj-65bec8e059.json
  bucket-name: tbms-firebase.appspot.com
  preview-url: https://firebasestorage.googleapis.com/v0/b/tbms-firebase.appspot.com/o/%s?alt=media

---

# application port
server:
  port: 8888
  error:
    include-stacktrace: never
  servlet:
    context-path: /tbms_service
  use-forward-headers: true

# spring setting
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/tbms-dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    sql-script-encoding: UTF-8
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    root: debug
    org.spring.framework: info
    com.shop.tbms: debug

# firebase
firebase:
  admin-key: ${ADMIN_KEY_FILE_PATH}
  bucket-name: ${BUCKET_NAME}
  preview-url: ${PREVIEW_URL}