# application port
server:
  port: 8888
  error:
    include-stacktrace: never
  servlet:
    context-path: /tbms_service

# spring setting
spring:
  datasource:
    url: jdbc:postgresql://58.84.1.74:5432/tbms
    username: admin
    password: 123
    sql-script-encoding: UTF-8
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update