# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
  push:
    branches: [ "master" ]

jobs:
  tbms-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build application
        run: |
          mvn clean install
      - name: Stop and Clear old service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}        
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }} 
          port: ${{ secrets.PORT }} 
          script: |
            sudo sh stop-tbms.sh
      - name: Upload application
        uses: appleboy/scp-action@master
        with:       
          host: ${{ secrets.HOST }}        
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }} 
          port: ${{ secrets.PORT }} 
          source: "/home/runner/work/tbms-service/tbms-service/target/tbms-build.jar"      
          target: "~/source"
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}        
          username: ${{ secrets.USERNAME }} 
          password: ${{ secrets.PASSWORD }} 
          port: ${{ secrets.PORT }} 
          script: |
            sudo sh start-tbms.sh
